package nl.ctmm.trait.proteomics.qcviewer.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import nl.ctmm.trait.proteomics.qcviewer.utils.Constants;
import nl.ctmm.trait.proteomics.qcviewer.utils.Utilities;

import org.apache.commons.io.FilenameUtils;
import org.jfree.ui.RefineryUtilities;

/**
 * The class for displaying information about the Report Viewer.
 *
 * @author <a href="mailto:pravin.pawar@nbic.nl">Pravin Pawar</a>
 * @author <a href="mailto:freek.de.bruijn@nbic.nl">Freek de Bruijn</a>
 */
public class AboutFrame extends JFrame implements ActionListener {
    /**
     * The logger for this class.
     */
    private static final Logger logger = Logger.getLogger(AboutFrame.class.getName());

    /**
     * The version number for (de)serialization of this class (UID: universal identifier).
     */
    private static final long serialVersionUID = 1;

    /**
     * Width of an individual button.
     */
    private static final int BUTTON_WIDTH = 80;

    /**
     * Height of an individual zoom button.
     */
    private static final int BUTTON_HEIGHT = 25;

    /**
     * Width of the about frame.
     */
    private static final int ABOUT_FRAME_WIDTH = 520;

    /**
     * Height of the about frame.
     */
    private static final int ABOUT_FRAME_HEIGHT = 740;

    /**
     * Width of the main panel.
     */
    private static final int MAIN_PANEL_WIDTH = 500;

    /**
     * Height of the main panel.
     */
    private static final int MAIN_PANEL_HEIGHT = 700;
    
    /**
     * Width of the scroll pane.
     */
    private static final int SCROLL_PANE_WIDTH = 500;

    /**
     * Height of the description text area.
     */
    private static final int DESCRIPTION_HEIGHT = 200;

    /**
     * Height of the references text area.
     */
    private static final int REFERENCES_HEIGHT = 150;

    /**
     * Height of the acknowledgements text area.
     */
    private static final int ACKNOWLEDGEMENTS_HEIGHT = 200;

    /**
     * Height of the details text area.
     */
    private static final int DETAILS_HEIGHT = 100;
    
    /**
     * The description for the application.
     *
     * TODO: fix special characters. [Freek]
     */
    private static final String DESCRIPTION =
        "Proteomics deals with the large-scale study of proteins and has become a powerful technology in "
        + "discovery of drug targets and biomarkers. Modern day proteomics is largely based on nano-liquid "
        + "chromatography coupled to high-resolution tandem mass spectrometry (nanoLC-MS/MS). However, the "
        + "reproducibility of MS results is considered by many as insufficient. In part, inadequate quality "
        + "control (QC) might be responsible for the lack of reproducibility [1].\n"
        + "The importance of well-established QC has become a focal point in the field of proteomics [2]. The "
        + "National Institute of Standards (NIST) has developed a QC pipeline for evaluating analytical "
        + "performance of a common discovery-based proteomics platform by monitoring selected output from a "
        + "LC-MS/MS system. This pipeline is known as NIST MSQC Pipeline [3]. The 46 QC metrics for monitoring "
        + "chromatographic performance, electrospray source stability, MS1 and MS2 signals, dynamic sampling of "
        + "ions for MS/MS, and peptide identification are described in [4]. Application of these metrics enables "
        + "rational, quantitative quality assessment for proteomics and other LC-MS/MS analytical applications.\n"
        + "The Netherlands Bioinformatics Centre (NBIC) has adapted the NIST MSQC Pipeline to suit the "
        + "proteomics QC requirements of the OncoProteomics Laboratory (OPL). The adapted pipeline is named as "
        + "NBIC-NIST MSQC Pipeline. Compared to the NIST MSQC Pipeline, the adapted version triggers pipeline "
        + "processing on the availability of a new RAW data file in a fully automatic fashionï¿½ and creates a "
        + "web-based QC report combining the NIST metrics with a number of custom metrics.  The custom-made MSQC "
        + "Report Viewer aggregates and shows all available QC reports generated by the MSQC pipeline report "
        + "directory. It includes functionality of sorting, filtering, zooming and comparing these reports as "
        + "per the need of proteomics researchers.";

    /**
     * The references for the application.
     *
     * TODO: fix special characters. [Freek]
     */
    private static final String REFERENCES =
            "[1] Köcher, T., Pichler, P., Swart, R. and Mechtler, K., Quality control in LC-MS/MS, Wiley "
            + "Proteomics, 11(6), pp. 1026-1030, Feb 2011.\n"
            + "[2] PRIME-XS-Deliverable 13.1, Deliverable 13.1 - Suite of tools that allow automatic quality control "
            + "on the acquired data, 16 Feb 2012.\n"
            + "[3] NIST LC-MS/MS Metrics for Monitoring Variability in Proteomics Experiments, National Institute of "
            + "Standards and Technology - United States Department of Commerce, June 2011, available online: "
            + "http://peptide.nist.gov/metrics/, last accessed: 22 Jan 2013.\n"
            + "[4] Rudnick P. A. et. al., Performance Metrics for Liquid Chromatography-Tandem Mass Spectrometry "
            + "Systems in Proteomics Analyses, Molecular and Cell Proteomics, 9(2), pp. 225-241, Feb 2010.";

    /**
     * The information for getting more details about the application.
     */
    private static final String DETAILS =
            "GitHub repository: https://github.com/CTMM-TraIT/trait_proteomics_qc_tool\n"
            + "Version: " + Constants.APPLICATION_VERSION + "\n"
            + "Contact: Dr. Thang V. Pham (t.pham@vumc.nl)";

    /**
     * The acknowledgement icon width and height.
     */
    private static final int ICON_SIZE = 100;
    
    /**
     * Message written to the logger in case of IOException while reading logo file.  
     */
    private static final String LOGO_NOT_FOUND_MESSAGE = "Logo in file %s not found.";

    /**
     * Constructor of the AboutFrame.
     */
    public AboutFrame() {
        super("About " + Constants.APPLICATION_NAME);
        // Create the main panel with the contents of this frame.
        final JPanel mainPanel = new JPanel(); 
        mainPanel.setLayout(new FlowLayout());
        mainPanel.setPreferredSize(new Dimension(MAIN_PANEL_WIDTH, MAIN_PANEL_HEIGHT));
        addScrollPane(mainPanel, createAboutTextArea(DESCRIPTION), "Proteomics Quality Control", DESCRIPTION_HEIGHT);
        addScrollPane(mainPanel, createAboutTextArea(REFERENCES), "References", REFERENCES_HEIGHT);
        addScrollPane(mainPanel, createAboutTextArea(DETAILS), "Download & Contact Details", DETAILS_HEIGHT);
        addScrollPane(mainPanel, createAcknowledgementsPanel(), "Acknowledgements", ACKNOWLEDGEMENTS_HEIGHT);
        final JButton okButton = new JButton(Constants.OK_BUTTON_TEXT);
        okButton.setSize(new Dimension(BUTTON_WIDTH, BUTTON_HEIGHT));
        okButton.addActionListener(this);
        okButton.setActionCommand(Constants.OK_BUTTON_TEXT);
        mainPanel.add(okButton);
        // Add the main panel to the frame and resize it.
        getContentPane().add(mainPanel);
        setBounds(0, 0, ABOUT_FRAME_WIDTH, ABOUT_FRAME_HEIGHT);
        RefineryUtilities.centerFrameOnScreen(this);
    }

    /**
     * Create a scroll pane with a view component inside of it and add it to the main panel.
     *
     * @param mainPanel the main panel.
     * @param view the view to put inside the scroll pane.
     * @param title the title of the scroll pane.
     * @param height the height of the scroll pane.
     */
    private void addScrollPane(final JPanel mainPanel, final Component view, final String title, final int height) {
        final JScrollPane scrollPane = new JScrollPane(view);
        scrollPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), title));
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setPreferredSize(new Dimension(SCROLL_PANE_WIDTH, height));
        scrollPane.setBackground(Color.WHITE);
        mainPanel.add(scrollPane);
    }

    /**
     * Create a text area with the specified text inside of it.
     *
     * @param text the specified text.
     * @return the text area with the specified text.
     */
    private JTextArea createAboutTextArea(final String text) {
        final JTextArea textArea = new JTextArea(text);
        textArea.setFont(Constants.PLAIN_FONT);
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        return textArea;
    }

    /**
     * Create the panel with the acknowledgements: logo's and links for all the partners involved in this project.
     *
     * @return the panel with the acknowledgements.
     */
    private JPanel createAcknowledgementsPanel() {
        final String[][] acknowledgementsData = {
            {"http://www.oncoproteomics.nl", Constants.OPL_LOGO_FILE_NAME},
            {"http://www.nist.gov", Constants.NIST_LOGO_FILE_NAME},
            {"http://www.ctmm.nl", Constants.CTMM_LOGO_FILE_NAME},
            {"http://www.ctmm-trait.nl", Constants.CTMM_TRAIT_LOGO_FILE_NAME},
            {"http://www.nbic.nl", Constants.NBIC_LOGO_FILE_NAME},
        };
        final JPanel acknowledgementsPanel = new JPanel();
        acknowledgementsPanel.setLayout(new GridLayout(acknowledgementsData.length, 1));
        acknowledgementsPanel.setBackground(Color.WHITE);
        for (final String[] acknowledgementData : acknowledgementsData) {
            acknowledgementsPanel.add(createAcknowledgementLabel(acknowledgementData[0], acknowledgementData[1]));
        }
        return acknowledgementsPanel;
    }

    /**
     * Create acknowledgement label with logo and link.
     *
     * @param link text of the acknowledgement label.
     * @param logoPath path to the logo.
     * @return a new label with logo and link.
     */
    private JLabel createAcknowledgementLabel(final String link, final String logoPath) {
        final JLabel label = new JLabel(link, JLabel.LEFT);
        try {
            final BufferedImage bufferedImage = ImageIO.read(new File(FilenameUtils.normalize(logoPath)));
            label.setIcon(new ImageIcon(Utilities.scaleImage(bufferedImage, 0, ICON_SIZE, ICON_SIZE)));
        } catch (final IOException e) {
            logger.log(Level.SEVERE, String.format(LOGO_NOT_FOUND_MESSAGE, FilenameUtils.normalize(logoPath)), e);
        }
        return label;
    }
    
    /**
     * Event handler for user actions such as pressing the OK button.
     *
     * @param actionEvent the action event.
     */
    @Override
    public void actionPerformed(final ActionEvent actionEvent) {
        if (actionEvent.getActionCommand().equals(Constants.OK_BUTTON_TEXT)) {
            dispose();
        }
    }
}
